"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.
# Updated for new Google OAuth credentials

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url


def env_bool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: list[str]) -> list[str]:
    value = os.environ.get(name)
    if not value:
        return default
    return [item.strip() for item in value.split(",") if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

DEBUG = env_bool("DEBUG", False)

# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-only-insecure-secret-key"
    else:
        raise RuntimeError("DJANGO_SECRET_KEY nao configurada.")

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", ["127.0.0.1", "localhost", "backend"])
# Cloud Run gera hostnames aleatórios.
# Aceita qualquer subdomínio do Cloud Run sem expor o hostname exato no código.
if ".a.run.app" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(".a.run.app")
if ".southamerica-east1.run.app" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(".southamerica-east1.run.app")


def build_social_app(client_id_env: str, secret_env: str, *, key_env: str | None = None):
    client_id = os.environ.get(client_id_env)
    secret = os.environ.get(secret_env)

    if not client_id or not secret:
        return None

    app = {
        "client_id": client_id,
        "secret": secret,
    }

    if key_env:
        app["key"] = os.environ.get(key_env, "")

    return app


INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.headless",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.linkedin_oauth2",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "encrypted_model_fields",
    "users",
    "jobs",
    "finances",
    "settings_app",
    "integrations",
    "messages.apps.MessagesConfig",
    "notifications",
    "channels",
]

AUTH_USER_MODEL = "users.User"

FIELD_ENCRYPTION_KEY = os.environ.get("FIELD_ENCRYPTION_KEY")
if not FIELD_ENCRYPTION_KEY:
    raise RuntimeError("FIELD_ENCRYPTION_KEY nao configurada.")

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "core.middleware.ApiSecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    ["http://localhost:3000", "https://ufreela.com.br", "https://www.ufreela.com.br"],
)
CORS_ALLOW_CREDENTIALS = True
# Permite tambem origens que casem com o regex (defesa contra env var mal preenchida).
CORS_ALLOWED_ORIGIN_REGEXES = env_list(
    "CORS_ALLOWED_ORIGIN_REGEXES",
    [r"^https://(www\.)?ufreela\.com\.br$"],
)

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    ["http://localhost:3000", "https://ufreela.com.br", "https://www.ufreela.com.br"],
)


if os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(
            default=os.environ.get("DATABASE_URL"),
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "freela"),
            "USER": os.environ.get("DB_USER", "freela_user"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "freela_pass"),
            "HOST": os.environ.get("DB_HOST", "db"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }

SITE_ID = 1
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")

# Garante que o host do FRONTEND_URL seja considerado seguro para redirects
# de login social (validação is_safe_url do Django/allauth).
# Força novo deploy para atualizar secrets.
try:
    from urllib.parse import urlparse

    _frontend_host = urlparse(FRONTEND_URL).hostname
    if _frontend_host and _frontend_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_frontend_host)
except Exception:
    pass


def _registered_domain(hostname: str) -> str:
    """Heuristica simples para extrair o dominio registrado de um hostname."""
    hostname = hostname.split(":")[0].lower()
    parts = hostname.split(".")
    if len(parts) <= 2:
        return hostname
    # eTLD de dois niveis (ex: com.br, co.uk): pega 3 partes.
    if len(parts[-1]) == 2 and len(parts[-2]) <= 3:
        return ".".join(parts[-3:])
    return ".".join(parts[-2:])


try:
    _frontend_host = urlparse(FRONTEND_URL).hostname or ""
    _share_site = any(
        _registered_domain(_frontend_host) == _registered_domain(host)
        for host in ALLOWED_HOSTS
        if host and not host.startswith(".")
    )
    _shared_domain = _registered_domain(_frontend_host) if _share_site else ""
except Exception:
    _share_site = False
    _shared_domain = ""

# Quando frontend e backend compartilham o dominio (ex: www.ufreela.com.br e
# api.ufreela.com.br), os cookies de sessao/CSRF precisam ter Domain=.ufreela.com.br
# para que o frontend consiga ler o csrftoken via JavaScript e enviar no header.
if _shared_domain:
    CSRF_COOKIE_DOMAIN = f".{_shared_domain}"
    SESSION_COOKIE_DOMAIN = f".{_shared_domain}"

STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
GITHUB_CLIENT_ID = os.environ.get("GITHUB_CLIENT_ID", "")
GITHUB_CLIENT_SECRET = os.environ.get("GITHUB_CLIENT_SECRET", "")
LINKEDIN_CLIENT_ID = os.environ.get("LINKEDIN_CLIENT_ID", "")
LINKEDIN_CLIENT_SECRET = os.environ.get("LINKEDIN_CLIENT_SECRET", "")
LINKEDIN_API_VERSION = os.environ.get("LINKEDIN_API_VERSION", "202601")
GITHUB_API_VERSION = os.environ.get("GITHUB_API_VERSION", "2026-03-10")

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

ACCOUNT_LOGIN_METHODS = {"username", "email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = os.environ.get("ACCOUNT_EMAIL_VERIFICATION", "mandatory")
# Logins sociais (Google, GitHub, LinkedIn) pulam verificacao de email porque
# o provedor OAuth ja garante que o email e verificado. Sem isso,
# ACCOUNT_EMAIL_VERIFICATION=mandatory faz o estagio de verificacao bloquear
# o adapter.login() -- o usuario nunca chega autenticado, e o frontend recebe
# 401 ao consultar /api/auth/social/session/. O setting do allauth
# (SOCIALACCOUNT_EMAIL_VERIFICATION) tem default None, que faz fallback para
# ACCOUNT_EMAIL_VERIFICATION, por isso precisamos definir explicitamente.
SOCIALACCOUNT_EMAIL_VERIFICATION = os.environ.get(
    "SOCIALACCOUNT_EMAIL_VERIFICATION", "none"
)
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_QUERY_EMAIL = True
# When a social provider returns a verified email that already belongs to a
# local user, log that user in and connect the social account automatically.
# Safe for trusted providers such as Google/GitHub.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

LOGIN_REDIRECT_URL = "/api/auth/social/success/"
LOGOUT_REDIRECT_URL = "/login/"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        **(
            {"APP": build_social_app("GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET")}
            if build_social_app("GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET")
            else {}
        ),
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"prompt": "select_account"},
    },
    "github": {
        **(
            {"APP": build_social_app("GITHUB_CLIENT_ID", "GITHUB_CLIENT_SECRET")}
            if build_social_app("GITHUB_CLIENT_ID", "GITHUB_CLIENT_SECRET")
            else {}
        ),
        "SCOPE": ["user:email"],
    },
    "linkedin_oauth2": {
        **(
            {"APP": build_social_app("LINKEDIN_CLIENT_ID", "LINKEDIN_CLIENT_SECRET")}
            if build_social_app("LINKEDIN_CLIENT_ID", "LINKEDIN_CLIENT_SECRET")
            else {}
        ),
        "SCOPE": ["r_liteprofile", "r_emailaddress"],
    },
}

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "users.authentication.CookieJWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
}


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.environ.get(
            "REDIS_CACHE_URL",
            os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1"),
        ),
    }
}

redis_url = os.environ.get("REDIS_URL")
if redis_url:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [redis_url],
            },
        },
    }
else:
    # Fallback para dev (InMemoryChannelLayer)
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }


STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ── Supabase Storage (S3-compatible) ─────────────────────
# Dois buckets, com propositos distintos:
#   - SUPABASE_PUBLIC_BUCKET (default): imagens publicas (avatar, portfolio).
#     Servidas por URL publica estavel, sem assinatura.
#   - SUPABASE_PRIVATE_BUCKET ("private"): anexos de conversas e documentos
#     sensiveis (LGPD). Acesso apenas por URLs assinadas temporarias geradas
#     pelo backend apos checagem de autorizacao (ver core/storages.py).
# ATENCAO: sem SUPABASE_S3_ENDPOINT no ambiente, o fallback e o disco local
# (efemero no Cloud Run) — os uploads nunca chegam ao bucket.
_supabase_s3_endpoint = os.environ.get("SUPABASE_S3_ENDPOINT", "").rstrip("/")
SUPABASE_PUBLIC_BUCKET = os.environ.get("SUPABASE_PUBLIC_BUCKET", "ufreela-public")
SUPABASE_PRIVATE_BUCKET = os.environ.get("SUPABASE_PRIVATE_BUCKET", "ufreela-private")
SUPABASE_S3_HOST = (
    urlparse(_supabase_s3_endpoint).netloc if _supabase_s3_endpoint else ""
)

if _supabase_s3_endpoint:
    STORAGES["default"]["BACKEND"] = "core.storages.SupabasePublicStorage"
    STORAGES["private"] = {"BACKEND": "core.storages.SupabasePrivateStorage"}

    AWS_ACCESS_KEY_ID = os.environ.get("SUPABASE_ACCESS_KEY")
    AWS_SECRET_ACCESS_KEY = os.environ.get("SUPABASE_SECRET_KEY")
    AWS_S3_ENDPOINT_URL = _supabase_s3_endpoint
    AWS_S3_REGION_NAME = os.environ.get("SUPABASE_REGION", "sa-east-1")
    # Supabase S3 exige enderecamento path-style ({endpoint}/{bucket}/{key})
    # e nao suporta ACLs por objeto — o acesso publico e definido no bucket
    # (marcar APENAS o bucket publico como "Public" no dashboard).
    AWS_S3_ADDRESSING_STYLE = "path"
else:
    # Dev local: disco. O "private" fica em subpasta propria para simular
    # a separacao dos buckets.
    STORAGES["private"] = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {"location": BASE_DIR / "media" / "private"},
    }


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "AUTH_HEADER_TYPES": ("Bearer",),
}

AUTH_COOKIE_ACCESS = "access_token"
AUTH_COOKIE_REFRESH = "refresh_token"
AUTH_COOKIE_SECURE = env_bool("AUTH_COOKIE_SECURE", not DEBUG)
AUTH_COOKIE_HTTPONLY = True
# Domain compartilhado com o frontend (ex: .ufreela.com.br) para que os
# cookies JWT sejam visiveis no middleware do Next.js (proxy.ts) rodando em
# www.ufreela.com.br. Sem isso, os cookies ficam restritos a
# api.ufreela.com.br e o middleware redireciona para /login.
AUTH_COOKIE_DOMAIN = f".{_shared_domain}" if _shared_domain else None
# SameSite depende de frontend e backend compartilharem o mesmo dominio
# registrado (ex: www.ufreela.com.br e api.ufreela.com.br -> ufreela.com.br).
# Mesmo site -> Lax; sites distintos -> None (requer Secure=True).
AUTH_COOKIE_SAMESITE = env_list(
    "AUTH_COOKIE_SAMESITE",
    ["Lax"] if (_share_site and AUTH_COOKIE_SECURE) else ["None"] if AUTH_COOKIE_SECURE else ["Lax"],
)[0]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
]


LANGUAGE_CODE = "pt-br"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

ASGI_APPLICATION = 'core.asgi.application'

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Limites de upload para reduzir risco de abuso por arquivos grandes.
FILE_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get("FILE_UPLOAD_MAX_MEMORY_SIZE", 5 * 1024 * 1024)
)
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get("DATA_UPLOAD_MAX_MEMORY_SIZE", 10 * 1024 * 1024)
)

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ── Email & SMTP Configuration ──────────────────────────────
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "uFreela <no-reply@ufreela.com.br>")

if DEBUG and not EMAIL_HOST_USER:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# ── Resend (Transactional Email API) ──────────────────────
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
RESEND_FROM_EMAIL = os.environ.get(
    "RESEND_FROM_EMAIL", "uFreela <noreply@ufreela.com.br>"
)

# ── Allauth Headless (SPA Auth API) ────────────────────────
HEADLESS_ONLY = True
HEADLESS_FRONTEND_URLS = {
    "socialaccount_login_error": f"{FRONTEND_URL}/auth/social/callback",
}

# ── Security & Throttling ──────────────────────────────────
# Rate limits para endpoints headless do allauth (login, signup, reset, etc.)
ACCOUNT_RATE_LIMITS = {
    "login": "5/m",
    "signup": "3/m",
    "reset_password": "3/m",
    "reset_password_from_key": "3/m",
}

REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = [
    "rest_framework.throttling.AnonRateThrottle",
    "rest_framework.throttling.UserRateThrottle",
]
REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
    "anon": "100/min",  # Previne bots varrendo a API
    "user": "1000/min", # Previne force brute de usuários logados
    "login": "5/min",                   # Brute-force de credenciais
    "register": "3/min",                # Abuso de criação de contas
    "password_reset": "3/min",          # Spam de e-mails de reset
    "password_reset_confirm": "5/min",  # Brute-force de token de reset
    "refresh": "10/min",                # Rotacao abusiva de refresh tokens
}

# ── Logging ───────────────────────────────────────────────
# Cloud Run: usa apenas console (logs vão para Cloud Logging).
# FileHandler foi removido pois o filesystem do Cloud Run é efêmero.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

if not DEBUG:
    # Render and most reverse proxies terminate TLS; let the proxy handle HTTP
    # -> HTTPS redirects instead of Django to avoid redirect loops.
    SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", False)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    # O Cloudflare Worker proxy encaminha o Host publico (api.ufreela.com.br)
    # via X-Forwarded-Host, mas o Cloud Run enxerga o proprio hostname
    # interno (*.run.app) no cabecalho Host. Sem essa flag, o
    # request.get_host()/build_absolute_uri() retornam a URL interna do
    # Cloud Run, quebrando redirect_uri do OAuth e URLs absolutas.
    # Seguro: Django valida X-Forwarded-Host contra ALLOWED_HOSTS.
    USE_X_FORWARDED_HOST = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    # SameSite=Lax quando frontend e backend compartilham o dominio;
    # SameSite=None quando sao sites distintos (cross-site).
    SESSION_COOKIE_SAMESITE = "Lax" if _share_site else "None"
    CSRF_COOKIE_SECURE = True
    # O cookie csrftoken precisa ser legivel pelo JavaScript do frontend
    # (SPA) para que ele possa ser enviado no cabecalho X-CSRFToken e no
    # campo csrfmiddlewaretoken do formulario de redirect do allauth
    # headless. HttpOnly=True quebra o fluxo OAuth e o axiosInterceptor.
    # A protecao contra CSRF continua garantida por:
    #   - CSRF_COOKIE_SAMESITE=Lax (ou None+Secure quando cross-site);
    #   - CSRF_COOKIE_SECURE=True;
    #   - CSRF_TRUSTED_ORIGINS (Django valida Origin/Referer);
    #   - core.middleware.ApiSecurityMiddleware (validacao extra de Origin).
    CSRF_COOKIE_HTTPONLY = False
    CSRF_COOKIE_SAMESITE = "Lax" if _share_site else "None"
    X_FRAME_OPTIONS = "DENY"
