# Generated by Django 6.0.4 on 2026-05-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('proposal_accepted', 'Proposta aceita'), ('proposal_rejected', 'Proposta recusada'), ('new_proposal', 'Nova proposta'), ('new_message', 'Nova mensagem'), ('payment_received', 'Pagamento recebido'), ('job_invitation', 'Convite para vaga'), ('profile_view', 'Visualização de perfil'), ('review_received', 'Avaliação recebida'), ('deadline_reminder', 'Lembrete de prazo')], max_length=30),
        ),
    ]
