services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=freela
      - POSTGRES_USER=freela_user
      - POSTGRES_PASSWORD=freela_pass

  redis:
    image: redis:7-alpine

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - ALLOWED_HOSTS=127.0.0.1,localhost,backend
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend/freela
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/freela:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - INTERNAL_API_URL=http://backend:8000/api
      - NODE_OPTIONS=--max-old-space-size=2048
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51TU8o9APTCG5nRHKZYCDHbI36x9WSDUG7SddK7KBET2GzuOQ4qf6fl1cZQMWHBbKjBKMyyo0o9wEOQisnw8554mK00fhxv1ViT
    depends_on:
      - backend         

volumes:
  postgres_data:
