# Generated by Django 6.0.4 on 2026-06-23 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='importededucation',
            name='linkedin_education_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importedexperience',
            name='linkedin_position_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='importededucation',
            unique_together={('user', 'linkedin_education_id')},
        ),
        migrations.AlterUniqueTogether(
            name='importedexperience',
            unique_together={('user', 'linkedin_position_id')},
        ),
    ]
