# Generated by Django 6.0.4 on 2026-05-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('pt-BR', 'Portugues (Brasil)'), ('en-US', 'English (US)'), ('es', 'Español')], default='pt-BR', max_length=10),
        ),
    ]
