CATALOG_SEED = [
    {
        "category_name": "Desenvolvimento Web",
        "category_slug": "desenvolvimento-web",
        "skills": [
            ("JavaScript", "javascript"),
            ("React", "react"),
            ("Next.js", "nextjs"),
            ("Angular", "angular"),
            ("Vue.js", "vuejs"),
            ("Node.js", "nodejs"),
            ("Django", "django"),
            ("PHP", "php"),
            ("Laravel", "laravel"),
            ("Java (Web)", "java-web"),
            ("WordPress", "wordpress"),
            ("WebFlow", "webflow"),
            ("Shopify", "shopify"),
            ("Ruby on Rails", "ruby-on-rails"),
        ],
    },
    {
        "category_name": "Desenvolvimento Mobile",
        "category_slug": "desenvolvimento-mobile",
        "skills": [
            ("Flutter", "flutter"),
            ("React Native", "react-native"),
            ("Swift", "swift"),
            ("Kotlin", "kotlin"),
            ("Desenvolvimento iOS", "desenvolvimento-ios"),
            ("Desenvolvimento Android", "desenvolvimento-android"),
        ],
    },
    {
        "category_name": "Inteligencia Artificial e Machine Learning",
        "category_slug": "ia-e-machine-learning",
        "skills": [
            ("Python", "python"),
            ("Machine Learning", "machine-learning"),
            ("Deep Learning", "deep-learning"),
            ("TensorFlow", "tensorflow"),
            ("PyTorch", "pytorch"),
            ("Processamento de Linguagem Natural (NLP)", "nlp"),
            ("Visao Computacional", "visao-computacional"),
            ("Integracao com ChatGPT/OpenAI", "integracao-openai"),
            ("Ciencia de Dados", "ciencia-de-dados"),
        ],
    },
    {
        "category_name": "DevOps e Infraestrutura",
        "category_slug": "devops-infraestrutura",
        "skills": [
            ("AWS (Amazon Web Services)", "aws"),
            ("Azure", "azure"),
            ("Google Cloud (GCP)", "gcp"),
            ("Docker", "docker"),
            ("Kubernetes", "kubernetes"),
            ("CI/CD", "ci-cd"),
            ("Bancos de Dados (SQL/NoSQL)", "bancos-de-dados"),
        ],
    },
    {
        "category_name": "Design e UX",
        "category_slug": "design-ux",
        "skills": [
            ("Figma", "figma"),
            ("Wireframing", "wireframing"),
            ("Miro", "miro"),
            ("Adobe XD", "adobe-xd"),
            ("Adobe Photoshop", "photoshop"),
            ("Adobe Illustrator", "illustrator"),
            ("UI Design", "ui-design"),
            ("UX Research", "ux-research"),
            ("Identidade Visual", "identidade-visual"),
            ("Criacao de Logos", "criacao-de-logos"),
        ],
    },
    {
        "category_name": "Marketing Digital",
        "category_slug": "marketing-digital",
        "skills": [
            ("SEO (Otimizacao)", "seo"),
            ("Google Ads", "google-ads"),
            ("Meta Ads (Facebook/Instagram)", "meta-ads"),
            ("Copywriting", "copywriting"),
            ("Email Marketing", "email-marketing"),
            ("Gestao de Trafego", "gestao-de-trafego"),
            ("Social Media", "social-media"),
            ("Google Analytics", "google-analytics"),
            ("Marketing de Conteudo", "marketing-conteudo"),
        ],
    },
    {
        "category_name": "Escrita e Traducao",
        "category_slug": "escrita-traducao",
        "skills": [
            ("Redacao Web", "redacao-web"),
            ("Criacao de Conteudo", "criacao-conteudo"),
            ("Revisao de Textos", "revisao-textos"),
            ("Traducao Ingles-Portugues", "traducao-en-pt"),
            ("Traducao Espanhol-Portugues", "traducao-es-pt"),
            ("Roteiros para Videos", "roteiros-videos"),
            ("Ghostwriting", "ghostwriting"),
        ],
    },
    {
        "category_name": "Video e Animacao",
        "category_slug": "video-animacao",
        "skills": [
            ("Edicao de Video", "edicao-video"),
            ("Adobe Premiere", "adobe-premiere"),
            ("After Effects", "after-effects"),
            ("Motion Design", "motion-design"),
            ("Animacao 2D", "animacao-2d"),
            ("Locucao", "locucao"),
            ("Criacao de Reels/Shorts", "criacao-reels-shorts"),
        ],
    },
    {
        "category_name": "Administrativo e Suporte",
        "category_slug": "administrativo-suporte",
        "skills": [
            ("Assistente Virtual", "assistente-virtual"),
            ("Atendimento ao Cliente", "atendimento-cliente"),
            ("Microsoft Excel", "excel"),
            ("Entrada de Dados (Data Entry)", "data-entry"),
            ("Pacote Office", "pacote-office"),
            ("Google Workspace", "google-workspace"),
        ],
    },
    {
        "category_name": "Financas e Negocios",
        "category_slug": "financas-negocios",
        "skills": [
            ("Contabilidade", "contabilidade"),
            ("Consultoria Financeira", "consultoria-financeira"),
            ("Criacao de Planos de Negocio", "planos-de-negocio"),
            ("Analise de Dados", "analise-de-dados"),
            ("Recrutamento e RH", "recrutamento-rh"),
            ("Power BI", "power-bi"),
        ],
    },
    {
        "category_name": "Direito e Consultoria",
        "category_slug": "direito-e-consultoria",
        "skills": [
            ("Direito Digital", "direito-digital"),
            ("Direito Trabalhista", "direito-trabalhista"),
            ("Direito Empresarial", "direito-empresarial"),
            ("Elaboracao de Contratos", "elaboracao-contratos"),
            ("Consultoria Empresarial", "consultoria-empresarial"),
            ("LGPD e Privacidade de Dados", "lgpd-privacidade"),
            ("Compliance", "compliance"),
        ],
    },
]
