# Generated by Django 6.0.4 on 2026-04-13 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerskill',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.freelancer'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='jobs.category'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='users.publisher'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='users.freelancer'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='jobs.opportunity'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='jobs.category'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='jobs.skill'),
        ),
        migrations.AddField(
            model_name='freelancerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancers', to='jobs.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('opportunity', 'freelancer')},
        ),
        migrations.AlterUniqueTogether(
            name='freelancerskill',
            unique_together={('freelancer', 'skill')},
        ),
    ]
