# Generated by Django 6.0.4 on 2026-06-23 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_contract_completion_approval'),
        ('jobs', '0005_add_deadline_to_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='jobs.opportunity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='job_id',
            field=models.CharField(blank=True, help_text='Legado — usar opportunity em vez disso.', max_length=64, null=True),
        ),
    ]
